server:
  port: 9787
  address: 0.0.0.0
spring:
  application:
    name: cle
  datasource:
    url: jdbc:mysql://47.120.59.10:3306/db_cle?useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  security:
    user:
      name: user
      password: 123456
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 300MB

  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    username: qigestare@gmail.com
    password: 2222
    port: 456
#mybatis三剑客配置
mybatis-plus:
  type-aliases-package: com.example.clebackend.*.entity
  mapper-locations: classpath:mapper/*.xml
  #驼峰命名自动转换，打印sql语句
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


uploadFileMode: local
fileSave:
  path: /www/wwwroot/cle-back-end/files/img/
  address: 47.120.59.10

salt:
  user: orz_orz_orz_114514_user
  shop: orz_orz_orz_114514_shop
  admin: orz_orz_orz_114514_admin



